import Head from "next/head";

export default function MainLayout({ children, side }) {
  return (
    <>
      <Head>
        <title>Livy - counselor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Image/logo.png" />
      </Head>
      <main>
        <div className='flex max-h-screen h-screen w-full text-sm overflow-hidden '>
          <div className='w-2/6 flex flex-col bg-green-50 h-screen  '>
            {side}
          </div>
          <div className="w-4/6 flex flex-col h-screen">
            {children}
          </div>
        </div>
      </main>
    </>
  )
}
